language: java
deploy:
  provider: heroku
  app: sysc4806project2020
  api_key:
    secure: Gf7tKRVbunBJ3nkqx/q6fzDznFhQWaQPfgSGyLZUHx08HCiuwsHgB0ROU3A5/v8MXSPlwc64vwzbRtItlVHS2Ju5ieu0801CvfQRh1idovrL72A6EgEPrJApcU17DAY9ZWCUx7U4q5yvrCAjsfWwra6GbMS/s+Bj2Qj8cW4Ht5CH3TriZhx9k1+N8FDqiMUS/8C/gSZZB69dwOorLVo2szeguXBp+/UO7VPNEOt7BQGUnSu4QY+jVoQMXGpATBqWKvN+/KIMqs5TueXfejXQQdqCs5hKCsZnqFV+9bzCiZC1EpYouLT/VDB+a/+6fzE37HT55dPFX7zcr8aDS/HKGrClncbmVFNdsEsjqwjYhbelI1dDWx05bTFjCohFe36IamWL3A9+i/rgEKEGJNaYp+AuvEI0pEnF/60pxeHK6S6zHzYZ3cl7A4f8p7afUZNK9dXwhWbt19HnqEZ49d0GIOWPV6epOa2eixBKw5oCpWmz6mTZyiWB7SIzQyJXM7LTR/gHk+69a0x0LfGPU9crIbPaHMyrFx2h6JFJV9o7FU5N4HFc5Nkj+TUQTCmAVilfMG0X7Dgxc5s8A+vtMCx/Qad/KCi8wUrLB1MJIg2vLndZDor3tAdQWpFCNH2bRx5R6Jj/cuGxfmdihYiZYP4v7FtJ5T84xBTWKhDlYf59kSY=
