language: java
deploy:
  provider: heroku
  app: sysc4806project2020
  api_key:
    secure: pnn7MsrbSBp2hxRoJO4Gv+PKY3p4GzoF7mUdX1r3eZ2mT0vgYtBH++7kuGLrQaZgWZd7yjPrLB3ddltdCDiZjXQPcjpa5qr9VGqZNSVincJ8KPd8mbRoR2AAgbdwhK62pLuLwzlZ/aSpM+gNuum/b47ATV481HePdvvJgWxqsxYXENODiJzUdcF2GYe1zXiAxYql5zZk9IUbSKVTzFMs2jOuICfLwgMfYZWUyEMwzcvwzAYaXZPlrMnTFE3TwmW1pMjJoFK7WuJ/H8hvxjmePcvWzME00TPUQBsUoP6Z4feb8O71m6cdp7BcGQhBc64/yA20ovdUvDksFaLeTTSn0E0HZDZX/BceNoCt2RO7GLTNeI6hk3+psf+0aZI7xPWmT5xfjnj2ATRoT3rOTfC1D99JQKnBdLkcKt5Orfr/HbxTemN+hAKgnyUmVulbz+acIHZRoAoms3JKcDgPXgpU8wGDbglVIUTt1qqFmd1lNhCC3EOvVekjPw8gumtM7FQpIua1t2OX1Y0kicR4aAF/P9z7rWfAKe2H3uX/zJQ1Zy7y5QOgLaZHqMJ6JTAW40wI0yOHdlbf0E4SeUYJZQI9qFMJfg6tMNOOjl4XAkIOOFzytDHSBBeGNLgRQ8maGRnmFaPPwfPRbK1CzbZVdackkay5sDvRTTKSdwvA4racs/o=
